# Generated by Django 3.2.14 on 2022-12-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fees', models.FloatField()),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dept', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'STUDENT_MASTER',
            },
        ),
    ]
